ABS_X: false
ABS_Y: false
ABS_Z: false
ABS_RX: false
ABS_RY: false
ABS_RZ: false
ABS_THROTTLE: false
ABS_RUDDER: false
ABS_WHEEL: false
ABS_GAS: false
ABS_BRAKE: false
ABS_HAT0X: false
ABS_HAT0Y: false
ABS_HAT1X: false
ABS_HAT1Y: false
ABS_HAT2X: false
ABS_HAT2Y: false
ABS_HAT3X: false
ABS_HAT3Y: false
ABS_PRESSURE: false
ABS_DISTANCE: false
ABS_TILT_X: false
ABS_TILT_Y: false
ABS_TOOL_WIDTH: false
ABS_VOLUME: false
ABS_MISC: false
ABS_MT_SLOT: false
ABS_MT_TOUCH_MAJOR: false
ABS_MT_TOUCH_MINOR: false
ABS_MT_WIDTH_MAJOR: false
ABS_MT_WIDTH_MINOR: false
ABS_MT_ORIENTATION: false
ABS_MT_POSITION_X: false
ABS_MT_POSITION_Y: false
ABS_MT_TOOL_TYPE: false
ABS_MT_BLOB_ID: false
ABS_MT_TRACKING_ID: false
ABS_MT_PRESSURE: false
ABS_MT_DISTANCE: false
ABS_MT_TOOL_X: false
ABS_MT_TOOL_Y: false