$(EmulatorDir): RETRODECKHOMEDIR/bios/rpcs3/
/dev_hdd0/: $(EmulatorDir)dev_hdd0/
/dev_hdd1/: $(EmulatorDir)dev_hdd1/
/dev_flash/: $(EmulatorDir)dev_flash/
/dev_flash2/: $(EmulatorDir)dev_flash2/
/dev_flash3/: $(EmulatorDir)dev_flash3/
/dev_bdvd/: $(EmulatorDir)dev_bdvd/
/games/: RETRODECKHOMEDIR/roms/ps3/
/app_home/: ""
/dev_usb***/:
  /dev_usb000:
    Path: $(EmulatorDir)dev_usb000/
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb001:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb002:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb003:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb004:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb005:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb006:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
  /dev_usb007:
    Path: ""
    Serial: ""
    VID: ""
    PID: ""
