name: Build Godot Project

on:
  push: {}
  pull_request: {}

env:
  TAG: v0.006

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build
        id: build
        uses: krynv/build-godot-action@v1.0.0
        with:
          name: gd-test
          preset: ${{ matrix.platform }}
          projectDir: "tools/configurator" # The project in the `test` directory will be built
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Upload Release Asset 🚀
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "Client - linux.zip"
          tag: ${{env.TAG}}
          overwrite: true
          file_glob: false