name: Building a mOnKeyX Project

on:
  push: 
    branches: [ feat/godot-uk ]
  pull_request: 
    branches: [ feat/godot-uk ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubunntu-latest
    
    steps:
      - uses: actions/checkout@v5
      - name : exportGame
        uses: firebelley/godot-export@v5.2.1
        with: 
          godot_executable_download_url: https://download.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://download.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          create_release: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
   
